server:
  port: 8081
#
#spring:
#  application:
#    name: 'provider'
#  datasource:
#    username: postgres
#    password: 12345
#    url: jdbc:postgresql://localhost:5432/store
#  jpa:
#    hibernate:
#      ddl-auto: update
#
spring:
  application:
    name: 'provider'
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    discovery:
      enabled: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8084/user


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true